### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by VikaAir** [ambrosus/airdao-mobile#107]
![photo_2023-06-26_13-43-39](https://github.com/ambrosus/airdao-mobile/assets/137767549/d88718d9-6238-4137-9de1-41a83c5bec2c)

- Logo is catted by top mobile bar. It's a common problem for many screens in the app. Negative space between page title and mobile bar.
- Remove dot in the last sentence.

**Comment by JavidHaji-zada** [comment]
Can you please list what other screens have you noticed this issue? @VikaAir

**Comment by VikaAir** [comment]
I noticed this issue on Welcome Screen, Base currency, Language and Notification settings
