### ISSUE TITLE
QR scan screen

### ISSUE THREAD

**Issue by VikaAir** [ambrosus/airdao-mobile#108]
It would be impossible to read under certain circumstances (too bright content on camera) white icon and white text. Camera tint can solve this issue:
![photo_2023-06-26_13-46-56](https://github.com/ambrosus/airdao-mobile/assets/137767549/e524be7c-a2d8-45d9-8b87-8553c5e4ba34)

**Comment by JavidHaji-zada** [comment]
Can you add a video snippet for this issue?

**Comment by VikaAir** [comment]
Uploading video_2023-06-28_11-38-55.mp4…
